[package]
name = "rtiow-gpu"
version = "0.1.0"
edition = "2024"

[dependencies]
wgpu = "25.0.2"
winit = "0.30.11"
bytemuck = "1.23.0"
pollster = "0.4.0"
env_logger = "0.11.8"
log = "0.4.27"
glam = { version = "0.30.4", features = ["bytemuck"] }
